apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger-grafana
  namespace: appmesh-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: flagger-grafana
  chart:
    repository: https://flagger.app
    name: grafana
    version: 1.4.0
  values:
    url: http://flagger-prometheus.appmesh-system:9090
