apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app: {{ include "app.fullname" . }}
    service: {{ .Values.service }}
    version: {{ .Values.version }}
spec:
  type: NodePort
  selector:
    app: {{ include "app.fullname" . }}
    service: {{ .Values.service }}
    version: {{ .Values.version }}
  ports:
    - name: http
      port: 80
      targetPort: 8088
      protocol: TCP