replicaCount: 2

image:
  tag: 1.0.0
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
containerPort: 80

resources:
  limits:
    cpu: 128m
    memory: 256Mi
  requests:
    cpu: 128m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

hpa:
  minReplicas: 2
  maxReplicas: 4
  targetAverageUtilization: 99

canary:
  progressDeadlineSeconds: 600 # default 600s
  service:
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: "gateway-error,client-error,stream-error"    
  analysis:
    interval: 10s # default 60s
    threshold: 10
    maxWeight: 50
    stepWeight: 10
    metrics:
      requestSuccessRate:
        threshold: 99
        interval: 1m
      requestDuration:
        threshold: 500
        interval: 30s
  loadTest:
    enabled: true
    url: http://flagger-loadtester.flagger/
    timeout: 5s
    cmd: hey -z 1m -q 10 -c 2 http://backend.flagger/
