apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: flagger
  namespace: flagger
spec:
  awsName: ingress-gateway
  httpRoute:
    match:
      prefix: /
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: api
