apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: flagger
  namespace: flagger
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ingress-gateway
              servicePort: 80
